name: Build and Test

on: push

jobs:

  build_and_deploy:
    name: Build and Test
    runs-on: ubuntu-20.04

    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        run: ./gradlew build
